name: 🚀 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ☁️ API
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm 9
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install global dependencies
        run: pnpm install

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: 'api-routes'
